// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfwnzibnrddglwdfxoak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmd256aWJucmRkZ2x3ZGZ4b2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDQyNzgsImV4cCI6MjA2MzY4MDI3OH0.1KPetwfqkX9-KZczalSjlvTnl3lNSCheYx0pD4xrs4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);